import type { Metadata } from 'next'
import { Inter, Teko, Montserrat, Merriweather, EB_Garamond } from 'next/font/google'
import './globals.css'
import './hero_overflow.css'

// export const inter = Inter({ subsets: ['latin'] })
export const montserrat = Montserrat({ weight: ['300', '500', '700', '800', '900'], style: ['normal', 'italic'], subsets: ['latin'] })
export const merriweather = Merriweather({ weight: ['300', '400', '700'], style: ['normal', 'italic'], subsets: ['latin'] })
export const teko = Teko({ weight: ['300', '400', '700'], style: ['normal'], subsets: ['latin'] })
export const eb_garamond = EB_Garamond({weight: ['500', '600'], style: ['normal'], subsets: ['latin']});



export const metadata: Metadata = {
  title: 'Demie Mistica - Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} max-w-5xl mx-auto blur-none`}>{children}</body>
    </html>
  )
}
